definitions:
  api_davudpasha.Action:
    properties:
      ActionParameters:
        description: Parameters of the action.
        items:
          $ref: '#/definitions/api_davudpasha.ActionParameter'
        type: array
      ActionRefId:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Reference ID for the action.
      ActionType:
        description: Type of the action.
        type: string
      Data:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Data associated with the action.
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.ActionDefinationsSearchRequest:
    properties:
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
      application:
        description: Specifies the application for which the action definitions are
          being searched.
        type: string
      searchFilter:
        description: Filter for searching action definations.
        type: string
      smartRestRequestContext:
        description: Context for the Smart REST request.
        type: string
    type: object
  api_davudpasha.ActionDefinationsSearchResponse:
    properties:
      Action:
        allOf:
        - $ref: '#/definitions/api_davudpasha.Action'
        description: Contains the details of the action.
      ActionDefinitionId:
        description: Unique identifier for the action definition.
        type: string
      Application:
        description: Specifies the application to which the action definition belongs.
        type: string
      Author:
        description: The author of the action definition.
        type: string
      Description:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Description of the action definition, which can be null.
      IsPublic:
        description: Indicates whether the action definition is public.
        type: boolean
      Name:
        description: Name of the action definition.
        type: string
      Type:
        description: Type of the action definition.
        type: string
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.ActionParameter:
    properties:
      Key:
        description: Key of the action parameter.
        type: string
      Value:
        description: Value of the action parameter.
        type: string
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.AssetsAsset:
    properties:
      _id:
        description: Unique identifier for the asset.
        type: string
      AssetId:
        description: Unique identifier for the asset.
        type: string
      AssetType:
        description: Type of the asset.
        type: string
      Credential:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Credential information for the asset, which can be null.
      CustomerId:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Identifier for the customer associated with the asset.
      DistinguishedName:
        description: Distinguished name of the asset.
        type: string
      EnterDate:
        description: Date when the asset was entered into the system.
        type: string
      GroupId:
        description: Identifier for the group to which the asset belongs.
        type: string
      HostName:
        description: Hostname of the asset.
        type: string
      InventoryInfo:
        allOf:
        - $ref: '#/definitions/api_davudpasha.AssetsInventoryInfo'
        description: Inventory information for the asset.
      Ip:
        description: IP address of the asset.
        type: string
      IsDeleted:
        description: Indicates whether the asset is deleted.
        type: boolean
      IsManage:
        description: Indicates whether the asset is manageable.
        type: boolean
      IsManuel:
        description: Indicates whether the asset was manually added.
        type: boolean
      IsPassive:
        description: Indicates whether the asset is passive.
        type: boolean
      LastAccessDate:
        description: Date of the last access to the asset.
        type: string
      LastUserOfSession:
        description: Last user who accessed the asset's session.
        type: string
      MacAddress:
        description: MAC address of the asset.
        type: string
      Name:
        description: Name of the asset.
        type: string
      ObjectGUID:
        description: Unique object GUID for the asset.
        type: string
      OsInfo:
        description: Information about the operating system of the asset.
        type: string
      ParentGroupIds:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableList-string'
        description: List of parent group IDs to which the asset belongs.
      Tag:
        description: List of tags associated with the asset.
        items:
          type: string
        type: array
      TagData:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Additional tag data, which can be null.
      TenantID:
        description: Unique identifier for the tenant.
        type: string
      Timestamp:
        allOf:
        - $ref: '#/definitions/github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString'
        description: Timestamp of when the asset was created or last updated.
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.AssetsInventoryInfo:
    properties:
      OperationSystemInfos:
        allOf:
        - $ref: '#/definitions/api_davudpasha.AssetsOperationSystemInfo'
        description: Information about the operating system of the asset.
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.AssetsOperationSystemInfo:
    properties:
      BuildNumber:
        description: Build number of the operating system.
        type: string
      Caption:
        description: Caption or name of the operating system.
        type: string
      Description:
        description: Description of the operating system.
        type: string
      Manufacturer:
        description: Manufacturer of the operating system.
        type: string
      OSArchitecture:
        description: Architecture of the operating system (e.g., 32-bit, 64-bit).
        type: string
      SerialNumber:
        description: Serial number of the operating system.
        type: string
      ServisPack:
        description: Service pack version of the operating system.
        type: string
      Version:
        description: Version of the operating system.
        type: string
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
    type: object
  api_davudpasha.AssetsSearchRequest:
    properties:
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
      pageNumber:
        description: Page number for pagination.
        type: integer
      pageSize:
        description: Number of items per page for pagination.
        type: integer
      searchFilter:
        description: Primary filter for searching assets.
        type: string
      searchFilter2:
        description: Secondary filter for searching assets.
        type: string
      smartRestRequestContext:
        description: Context for the Smart REST request.
        type: string
    type: object
  api_davudpasha.AssetsSearchResponse:
    properties:
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
      assets:
        description: List of assets matching the search criteria.
        items:
          $ref: '#/definitions/api_davudpasha.AssetsAsset'
        type: array
      count:
        description: Total count of assets matching the search criteria.
        type: integer
    type: object
  api_davudpasha.ErrorResponse:
    properties:
      additionalProperties:
        additionalProperties: true
        description: Additional properties not defined in the struct.
        type: object
      errors:
        description: A list of errors
        items:
          type: string
        type: array
    type: object
  github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableList-string:
    type: object
  github_com_mtnmunuklu_davudpasha-api-client-go_api_common.NullableString:
    type: object
info:
  contact: {}
paths:
  /IAlertAct/GetActionDefinitions:
    post:
      consumes:
      - application/json
      description: Search for action definitions based on a query.
      parameters:
      - description: Search Action Definitions Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api_davudpasha.ActionDefinationsSearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            items:
              $ref: '#/definitions/api_davudpasha.ActionDefinationsSearchResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Search Action Definitions
      tags:
      - ActionDefinations
  /IAssetAct/GetAllAsset2:
    post:
      consumes:
      - application/json
      description: Retrieve assets that match a search filter.
      parameters:
      - description: Search Assets Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api_davudpasha.AssetsSearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/api_davudpasha.AssetsSearchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api_davudpasha.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Search Assets
      tags:
      - Assets
swagger: "2.0"
